spring:
  application:
    name: spring-boot-my-sql

  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_my_sql
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    root: info
    com.sts: debug
    org.springframework.web: debug
    org.hibernate: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} [%file:%line] - %msg%n"