version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spring-boot-my-sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spring_boot_my_sql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: